### PR TITLE
Updating encoder launch endpoint to provide tenant id

### PR DESCRIPTION
**Pull request by ktonon**
launch

### CODE REVIEW

**Comment by ktonon** [comment]
I haven't tested this locally. How is that done?

**Comment by ktonon** [comment]
Tried testing locally, but the capture central link was still going to what looks like the old version. Complaining about missing lti secret and portal url. I'm updating my lms and doing a full_all now...

**Comment by ktonon** [comment]
Think I'm missing a feature flag

**Comment by ktonon** [comment]
I was missing `d2l.Tools.Capture.UseContentService` to `on`

**Comment by ktonon** [comment]
Tested locally and the encoder was launched with the correct remote command

**Review by gordon-plumb — APPROVED** [review]

**Pull request merged**
